# References:
# 1. https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# 2. https://circleci.com/docs/2.0/building-docker-images/
#

version: 2
jobs:
  build_bmo:
    working_directory: /app
    docker:
      - image: docker:17.06.1-ce
    steps:
      - setup_remote_docker
      - run:
          name: install git and ssh
          command: apk update && apk add git openssh-client make bash perl perl-ipc-run3
      - checkout
      - run: make DIRS=bmo/ snapshots
      - store_artifacts:
          path: /app/bmo/vendor.tar.gz
          destination: bmo.tar.gz
      - store_artifacts:
          path: /app/bmo/build.log
          destination: bmo-build.log
      - store_artifacts:
          path: /app/bmo/run.log
          destination: bmo-run.log

  build_mozreview:
    working_directory: /app
    docker:
      - image: docker:17.06.1-ce
    steps:
      - setup_remote_docker
      - run:
          name: install git and ssh
          command: apk update && apk add git openssh-client make bash perl perl-ipc-run3
      - checkout
      - run: make DIRS=mozreview/ snapshots
      - store_artifacts:
          path: /app/bmo/mozreview.tar.gz
          destination: mozreview.tar.gz
      - store_artifacts:
          path: /app/mozreview/build.log
          destination: mozreview-build.log
      - store_artifacts:
          path: /app/mozreview/run.log
          destination: mozreview-run.log

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_bmo
      - build_mozreview
