# References:
# 1. https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# 2. https://circleci.com/docs/2.0/building-docker-images/
#

version: 2
jobs:
  build_bmo:
    working_directory: /app
    docker:
      - image: docker:17.06.1-ce
    steps:
      - setup_remote_docker
      - run:
          name: install build (host) dependencies
          command: apk update && apk add git openssh-client make bash perl perl-ipc-run3
      - checkout
      - run: make DIRS=bmo/ snapshots
      - store_artifacts:
          path: /app/bmo/vendor.tar.gz
          destination: bmo.tar.gz

  build_bmo_centos7:
    working_directory: /app
    docker:
      - image: docker:17.06.1-ce
    steps:
      - setup_remote_docker
      - run:
          name: install build (host) dependencies
          command: apk update && apk add git openssh-client make bash perl perl-ipc-run3
      - checkout
      - run: make DIRS=bmo_centos7/ snapshots
      - store_artifacts:
          path: /app/bmo_centos7/vendor.tar.gz
          destination: bmo_centos7.tar.gz

  build_mozreview:
    working_directory: /app
    docker:
      - image: docker:17.06.1-ce
    steps:
      - setup_remote_docker
      - run:
          name: install build (host) dependencies
          command: apk update && apk add git openssh-client make bash perl perl-ipc-run3
      - checkout
      - run: make DIRS=mozreview/ snapshots
      - store_artifacts:
          path: /app/bmo/mozreview.tar.gz
          destination: mozreview.tar.gz

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_bmo
      - build_bmo_centos7
      - build_mozreview
